---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-template
  name: webapp-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-template
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-image: hashicorp/vault-enterprise:1.4.0_ent
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/secret-volume-path-token: /root/
        vault.hashicorp.com/role: example
        vault.hashicorp.com/namespace: cluster-1
      labels:
        app: webapp-template
    spec:
      serviceAccountName: webapp
      containers:
      - image: webapp-template:v1
        name: webapp-template
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
          - containerPort: 5000
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-template
  name: webapp-template
spec:
  type: NodePort
  ports:
  - port: 5000
  selector:
    app: webapp-template